services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  db:
    image: bitnami/mongodb:5.0.17
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: my_database

volumes:
  mongodb_data:
    driver: local